2023-11-01 12:09:42,105 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:11:06,657 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:11:07,000 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:12:29,986 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:14:38,887 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:15:28,398 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:15:33,410 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:15:39,305 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:15:42,148 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:16:52,541 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:20:54,544 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:20:54,647 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:20:54,803 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:20:54,958 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:21:06,440 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:27:15,900 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:36:03,098 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:37:42,391 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:37:49,738 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:41:13,724 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz:80'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz:80'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:41:15,044 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz:80'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz:80'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:41:16,312 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:41:16,672 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 12:45:37,213 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 13:02:04,170 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 13:02:05,091 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 13:02:29,906 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 13:28:34,315 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz'. You may need to add 'zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 13:55:23,074 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.zayadev.xyz'. You may need to add 'www.zayadev.xyz' to ALLOWED_HOSTS.
2023-11-01 14:06:07,018 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:06:08,614 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:06:15,456 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:08:58,870 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:09:00,257 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:15:37,501 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:15:44,553 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:15:46,598 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:15:48,008 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:15:49,203 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:16:50,720 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:16:52,174 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:27:31,115 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:29:41,368 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:36:49,673 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 14:55:48,231 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
[2023-11-01 14:06:02 +0000] [5496] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 1000
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /opt/usr/devs/portfolio/my-resume
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /opt/usr/devs/portfolio/my-resume/logs/app.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /opt/usr/devs/portfolio/my-resume/logs/app.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: portfolio.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f19374e7a30>
  on_reload: <function OnReload.on_reload at 0x7f19374e7b50>
  when_ready: <function WhenReady.when_ready at 0x7f19374e7c70>
  pre_fork: <function Prefork.pre_fork at 0x7f19374e7d90>
  post_fork: <function Postfork.post_fork at 0x7f19374e7eb0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f19374fc040>
  worker_int: <function WorkerInt.worker_int at 0x7f19374fc160>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f19374fc280>
  pre_exec: <function PreExec.pre_exec at 0x7f19374fc3a0>
  pre_request: <function PreRequest.pre_request at 0x7f19374fc4c0>
  post_request: <function PostRequest.post_request at 0x7f19374fc550>
  child_exit: <function ChildExit.child_exit at 0x7f19374fc670>
  worker_exit: <function WorkerExit.worker_exit at 0x7f19374fc790>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f19374fc8b0>
  on_exit: <function OnExit.on_exit at 0x7f19374fc9d0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-11-01 14:06:02 +0000] [5496] [INFO] Starting gunicorn 20.1.0
[2023-11-01 14:06:02 +0000] [5496] [DEBUG] Arbiter booted
[2023-11-01 14:06:02 +0000] [5496] [INFO] Listening at: http://0.0.0.0:8000 (5496)
[2023-11-01 14:06:02 +0000] [5496] [INFO] Using worker: sync
[2023-11-01 14:06:02 +0000] [5497] [INFO] Booting worker with pid: 5497
[2023-11-01 14:06:02 +0000] [5498] [INFO] Booting worker with pid: 5498
[2023-11-01 14:06:02 +0000] [5499] [INFO] Booting worker with pid: 5499
[2023-11-01 14:06:02 +0000] [5496] [DEBUG] 3 workers
2023-11-01 15:06:15,689 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 15:07:25,413 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 15:08:34,561 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 15:11:00,708 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
[2023-11-01 14:14:54 +0000] [5496] [INFO] Handling signal: term
[2023-11-01 14:14:54 +0000] [5496] [WARNING] Worker with pid 5497 was terminated due to signal 15
[2023-11-01 14:14:54 +0000] [5496] [WARNING] Worker with pid 5499 was terminated due to signal 15
[2023-11-01 14:14:54 +0000] [5496] [WARNING] Worker with pid 5498 was terminated due to signal 15
[2023-11-01 14:14:54 +0000] [5496] [INFO] Shutting down: Master
[2023-11-01 14:14:54 +0000] [5794] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 1000
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /opt/usr/devs/portfolio/my-resume
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /opt/usr/devs/portfolio/my-resume/logs/app.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /opt/usr/devs/portfolio/my-resume/logs/app.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: portfolio.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fbd21baba30>
  on_reload: <function OnReload.on_reload at 0x7fbd21babb50>
  when_ready: <function WhenReady.when_ready at 0x7fbd21babc70>
  pre_fork: <function Prefork.pre_fork at 0x7fbd21babd90>
  post_fork: <function Postfork.post_fork at 0x7fbd21babeb0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fbd21bc0040>
  worker_int: <function WorkerInt.worker_int at 0x7fbd21bc0160>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fbd21bc0280>
  pre_exec: <function PreExec.pre_exec at 0x7fbd21bc03a0>
  pre_request: <function PreRequest.pre_request at 0x7fbd21bc04c0>
  post_request: <function PostRequest.post_request at 0x7fbd21bc0550>
  child_exit: <function ChildExit.child_exit at 0x7fbd21bc0670>
  worker_exit: <function WorkerExit.worker_exit at 0x7fbd21bc0790>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fbd21bc08b0>
  on_exit: <function OnExit.on_exit at 0x7fbd21bc09d0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-11-01 14:14:54 +0000] [5794] [INFO] Starting gunicorn 20.1.0
[2023-11-01 14:14:54 +0000] [5794] [DEBUG] Arbiter booted
[2023-11-01 14:14:54 +0000] [5794] [INFO] Listening at: http://0.0.0.0:8000 (5794)
[2023-11-01 14:14:54 +0000] [5794] [INFO] Using worker: sync
[2023-11-01 14:14:54 +0000] [5795] [INFO] Booting worker with pid: 5795
[2023-11-01 14:14:54 +0000] [5796] [INFO] Booting worker with pid: 5796
[2023-11-01 14:14:54 +0000] [5797] [INFO] Booting worker with pid: 5797
[2023-11-01 14:14:54 +0000] [5794] [DEBUG] 3 workers
2023-11-01 15:15:08,870 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
2023-11-01 15:15:10,246 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/usr/devs/portfolio/my-resume/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'zayadev.xyz,zayadev.xyz'. The domain name provided is not valid according to RFC 1034/1035.
[2023-11-01 19:20:48 +0000] [5794] [INFO] Handling signal: term
[2023-11-01 19:20:48 +0000] [5794] [WARNING] Worker with pid 5795 was terminated due to signal 15
[2023-11-01 19:20:48 +0000] [5794] [WARNING] Worker with pid 5796 was terminated due to signal 15
[2023-11-01 19:20:48 +0000] [5794] [WARNING] Worker with pid 5797 was terminated due to signal 15
[2023-11-01 19:20:48 +0000] [5794] [INFO] Shutting down: Master
[2023-11-01 19:22:08 +0000] [10029] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 1000
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /opt/usr/devs/portfolio/my-resume
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /opt/usr/devs/portfolio/my-resume/logs/app.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /opt/usr/devs/portfolio/my-resume/logs/app.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: portfolio.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f6bc643ba30>
  on_reload: <function OnReload.on_reload at 0x7f6bc643bb50>
  when_ready: <function WhenReady.when_ready at 0x7f6bc643bc70>
  pre_fork: <function Prefork.pre_fork at 0x7f6bc643bd90>
  post_fork: <function Postfork.post_fork at 0x7f6bc643beb0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f6bc6450040>
  worker_int: <function WorkerInt.worker_int at 0x7f6bc6450160>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f6bc6450280>
  pre_exec: <function PreExec.pre_exec at 0x7f6bc64503a0>
  pre_request: <function PreRequest.pre_request at 0x7f6bc64504c0>
  post_request: <function PostRequest.post_request at 0x7f6bc6450550>
  child_exit: <function ChildExit.child_exit at 0x7f6bc6450670>
  worker_exit: <function WorkerExit.worker_exit at 0x7f6bc6450790>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f6bc64508b0>
  on_exit: <function OnExit.on_exit at 0x7f6bc64509d0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-11-01 19:22:08 +0000] [10029] [INFO] Starting gunicorn 20.1.0
[2023-11-01 19:22:08 +0000] [10029] [DEBUG] Arbiter booted
[2023-11-01 19:22:08 +0000] [10029] [INFO] Listening at: http://0.0.0.0:8000 (10029)
[2023-11-01 19:22:08 +0000] [10029] [INFO] Using worker: sync
[2023-11-01 19:22:08 +0000] [10030] [INFO] Booting worker with pid: 10030
[2023-11-01 19:22:08 +0000] [10031] [INFO] Booting worker with pid: 10031
[2023-11-01 19:22:08 +0000] [10032] [INFO] Booting worker with pid: 10032
[2023-11-01 19:22:08 +0000] [10029] [DEBUG] 3 workers
